#! /usr/bin/bash

function error {
  printf "\e[31mInvalid argument!\e[0m\n"
  printf "Usage: runDebug [-b] [-a <args>] -e <executable>\n"
  printf "  -b: Build the application\n"
  printf "  -a: Arguments for the application\n"
  printf "  -e: Path to the executable\n"
  exit 1
}
function build {
  echo "Building application..."
  cmake --build build/Debug 1> /dev/null 2> /dev/tty
}

ARGS=""
EXECUTABLE=""
while getopts "ba:e:" o; do
  case $o in
    (b) build;;
    (a) ARGS=$OPTARG;;
    (e) EXECUTABLE=$OPTARG;;
    (*) error
  esac
done

if [ -z "$EXECUTABLE" ]; then
  if [ -f ".cache/lastExecutable" ]; then
    EXECUTABLE=$(cat .cache/lastExecutable)
  else
    printf "\e[31mNo executable found!\e[0m\n"
    echo "Please provide a path to the executable with -e"
    exit 1
  fi
else
  mkdir .cache 2> /dev/null
  echo $EXECUTABLE > .cache/lastExecutable
fi



currentDateTime=$(date +"%H%M%S-%d%m%Y")
COLUMNS=$(tput cols)
COUNTER=0
VDIV=""
while [ $COUNTER -lt $COLUMNS ]; do
  VDIV+="_"
  COUNTER=$(($COUNTER + 1))
done
printf "%s\n" "$VDIV"
printf "\n\e[3m Starting programm... \e[0m\n"
sleep 0.2

startSecond=$(date +%s%N)
printf "%s\n\n" "$VDIV"
printf "\e[32m"
if [ $COLUMNS -gt 102 ]; then
  ./$EXECUTABLE $ARGS |& tee logs/log${currentDateTime}.txt \
    | ts '[%d.%m.%Y %H:%M:%S]'
else
  ./$EXECUTABLE $ARGS |& tee logs/log${currentDateTime}.txt
fi
printf "\e[0m"

endSecond=$(date +%s%N)

miliSecondDiff=$(((endSecond - startSecond)/1000000))
printf "\n%s\n" "$VDIV"
printf "\n\e[3m%s\nRuntime: \e[0m\e[1m%s\e[0m\e[3m\n%s\e[0m\n"\
  "Programm has finished!"\
  "${miliSecondDiff}ms" \
  "See logs for more details"
printf "%s\n" "$VDIV"
sleep 0.5
while [ $(ls logs -1 | wc -l) -gt 10 ]; do
  echo -e "\e[33mMore then 10 log files have been found!"
  oldestFile="$(ls logs/ -rt | head -n 1)"
  printf "Deleting \e[3m%s\e[0m\n" "$oldestFile"
  rm -- logs/$oldestFile
  sleep 0.2
done
